title: 787 ECL Emulator
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a 787 ECL emulator. It is cross platform and it can be installed on iOS, Android and Desktop for offline access. The format is based on the paper QRH of one specific airline.
  It is not meant to replicate the functionality of the aircraft-installed ECL. Not for official nor training use.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
sass:
  sass_dir: assets/css

exclude:
  - task.sh
  - scratch-pad.txt

# My setting
developer: Sayed Ali Alwedaie
app_url: 787-ecl.com
last_updated: 23 AUG 2022
iban: BH45BIBB00200001342583
